<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot-starters</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-boot-starter-license-server</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <name>smart-boot-starter-license-server</name>
    <description>license server starter</description>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-license-server</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
