<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.smart</groupId>
    <artifactId>smart-boot</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <name>smart-boot</name>
    <description>Smart boot 通用开发框架</description>
    <properties>
        <java.version>25</java.version>
        <resource.delimiter>@</resource.delimiter>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <spring-boot.version>4.0.0</spring-boot.version>
        <spring-cloud.version>2025.1.0</spring-cloud.version>
        <spring-cloud-alibaba.version>2025.0.0.0</spring-cloud-alibaba.version>

        <guava.version>33.5.0-jre</guava.version>
        <commons-collections4.version>4.5.0</commons-collections4.version>
        <commons-beanutils.version>1.11.0</commons-beanutils.version>
        <spring-security-saml2.version>1.0.10.RELEASE</spring-security-saml2.version>
        <swagger-annotations.version>2.2.34</swagger-annotations.version>
        <commons-io.version>2.17.0</commons-io.version>
        <jsch.version>0.1.55</jsch.version>

        <mybatis-plus.version>3.5.15</mybatis-plus.version>
        <jodconverter.version>4.4.11</jodconverter.version>
        <google.zxing.version>3.5.3</google.zxing.version>
        <!--    TODO:大版本升级3.0.0    -->
        <jxls.version>2.14.0</jxls.version>
        <jacob.version>1.20</jacob.version>
        <kettle.version>10.2.0.0-222</kettle.version>
        <xxl-job.version>3.2.0</xxl-job.version>
        <druid.version>1.2.27</druid.version>
        <easy-captcha.version>1.6.2</easy-captcha.version>
        <ojdbc8.version>19.3.0.0</ojdbc8.version>
        <commons-vfs2.version>2.10.0</commons-vfs2.version>
        <scannotation.version>1.0.3</scannotation.version>
        <nimbus-jose-jwt.version>10.4.2</nimbus-jose-jwt.version>
        <truelicense.version>1.33</truelicense.version>
        <minio.version>8.6.0</minio.version>
        <hutool.version>5.8.40</hutool.version>
        <aliyun.oss.version>3.18.3</aliyun.oss.version>
        <knife4j-openapi3.version>4.5.0</knife4j-openapi3.version>
        <qiniu.version>7.19.0</qiniu.version>
        <wx-java.version>4.7.0</wx-java.version>
        <aliyun.dysmsapi.version>3.1.0</aliyun.dysmsapi.version>
        <tencentcloud.sdk.version>3.1.1281</tencentcloud.sdk.version>
        <tianai-captcha.version>1.5.3</tianai-captcha.version>
        <commons-net.version>3.12.0</commons-net.version>
        <nacos.logback-adapter.version>1.1.4</nacos.logback-adapter.version>
        <nashorn.version>15.7</nashorn.version>
        <amazon.aws.version>2.5.31</amazon.aws.version>
        <dingtalk.server.new.version>2.2.33</dingtalk.server.new.version>
        <dingtalk.server.old.version>2.0.0</dingtalk.server.old.version>
        <redisson.version>3.51.0</redisson.version>
        <libphonenumber.version>9.0.19</libphonenumber.version>
        <bcprov-jdk15on.version>1.70</bcprov-jdk15on.version>
        <grpc-netty.version>1.75.0</grpc-netty.version>
        <langchain4j.version>1.3.0</langchain4j.version>
        <aliyun.ocr.version>3.1.3</aliyun.ocr.version>
        <springdoc.version>2.8.9</springdoc.version>
        <jsqlparser.version>5.1</jsqlparser.version>
        <alibaba.transmittable.version>2.14.5</alibaba.transmittable.version>
        <pdfbox.version>3.0.5</pdfbox.version>
        <bouncycastle.version>1.82</bouncycastle.version>
    </properties>

    <packaging>pom</packaging>

    <modules>
        <module>smart-boot-framework</module>
        <module>smart-framework</module>
        <module>smart-cloud-framework</module>
        <module>smart-cloud-services</module>
        <module>smart-module-api</module>
        <module>smart-modules</module>
        <module>smart-services</module>
    </modules>

    <developers>
        <developer>
            <id>zhongming4762</id>
            <name>zhongming4762</name>
            <email>zhongming4762@hotmail.com</email>
        </developer>
    </developers>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <profiles.active>dev</profiles.active>
                <nacos.server-addr>127.0.0.1:8848</nacos.server-addr>
                <nacos.ip>127.0.0.1</nacos.ip>
                <nacos.namespace>dev</nacos.namespace>
                <nacos.username>nacos</nacos.username>
                <nacos.password>nacos</nacos.password>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>pro</id>
            <properties>
                <profiles.active>pro</profiles.active>

                <nacos.server-addr>127.0.0.1:8848</nacos.server-addr>
                <nacos.namespace>pro</nacos.namespace>
                <nacos.username>nacos</nacos.username>
                <nacos.password>nacos</nacos.password>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!--	  springboot		-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--      spring cloud      -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--      spring-cloud-alibaba      -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-commons-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-message-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-vfs2</artifactId>
                <version>${commons-vfs2.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons-collections4.version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger-annotations.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <dependency>
                <groupId>com.jcraft</groupId>
                <artifactId>jsch</artifactId>
                <version>${jsch.version}</version>
            </dependency>

            <!--mybatis-plus支持-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-extension</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.whvcse</groupId>
                <artifactId>easy-captcha</artifactId>
                <version>${easy-captcha.version}</version>
            </dependency>

            <dependency>
                <groupId>org.jodconverter</groupId>
                <artifactId>jodconverter-spring-boot-starter</artifactId>
                <version>${jodconverter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jodconverter</groupId>
                <artifactId>jodconverter-local</artifactId>
                <version>${jodconverter.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${google.zxing.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>javase</artifactId>
                <version>${google.zxing.version}</version>
            </dependency>

            <dependency>
                <groupId>org.jxls</groupId>
                <artifactId>jxls-poi</artifactId>
                <version>${jxls.version}</version>
            </dependency>

            <dependency>
                <groupId>com.jacob</groupId>
                <artifactId>jacob</artifactId>
                <version>${jacob.version}</version>
            </dependency>

            <!--  kettle版本号	-->
            <dependency>
                <groupId>org.pentaho</groupId>
                <artifactId>kettle-core</artifactId>
                <version>${kettle.version}</version>
            </dependency>
            <!--引入kettle支持-->
            <dependency>
                <groupId>org.pentaho</groupId>
                <artifactId>kettle-engine</artifactId>
                <version>${kettle.version}</version>
            </dependency>
            <dependency>
                <groupId>org.pentaho</groupId>
                <artifactId>pentaho-encryption-support</artifactId>
                <version>${kettle.version}</version>
            </dependency>
            <!--引入kettle支持-->
            <dependency>
                <groupId>org.pentaho</groupId>
                <artifactId>metastore</artifactId>
                <version>${kettle.version}</version>
            </dependency>
            <dependency>
                <groupId>org.pentaho</groupId>
                <artifactId>commons-xul-core</artifactId>
                <version>${kettle.version}</version>
            </dependency>

            <dependency>
                <groupId>org.scannotation</groupId>
                <artifactId>scannotation</artifactId>
                <version>${scannotation.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk15on</artifactId>
                <version>${bcprov-jdk15on.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xuxueli</groupId>
                <artifactId>xxl-job-core</artifactId>
                <version>${xxl-job.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>com.oracle.ojdbc</groupId>
                <artifactId>ojdbc8</artifactId>
                <version>${ojdbc8.version}</version>
            </dependency>

            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>${nimbus-jose-jwt.version}</version>
            </dependency>
            <dependency>
                <groupId>de.schlichtherle.truelicense</groupId>
                <artifactId>truelicense-core</artifactId>
                <version>${truelicense.version}</version>
            </dependency>
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <!--      阿里云OSS版本      -->
            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun.oss.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
                <version>${knife4j-openapi3.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j-openapi3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>

            <dependency>
                <groupId>com.qiniu</groupId>
                <artifactId>qiniu-java-sdk</artifactId>
                <version>${qiniu.version}</version>
            </dependency>

            <!--      微信工具类      -->
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-miniapp</artifactId>
                <version>${wx-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-pay</artifactId>
                <version>${wx-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-mp</artifactId>
                <version>${wx-java.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>dysmsapi20170525</artifactId>
                <version>${aliyun.dysmsapi.version}</version>
            </dependency>

            <dependency>
                <groupId>com.tencentcloudapi</groupId>
                <artifactId>tencentcloud-sdk-java</artifactId>
                <version>${tencentcloud.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tencentcloudapi</groupId>
                <artifactId>tencentcloud-sdk-java-sms</artifactId>
                <version>${tencentcloud.sdk.version}</version>
            </dependency>
            <!--      验证码组件      -->
            <dependency>
                <groupId>cloud.tianai.captcha</groupId>
                <artifactId>tianai-captcha</artifactId>
                <version>${tianai-captcha.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.tianai.captcha</groupId>
                <artifactId>tianai-captcha-springboot-starter</artifactId>
                <version>${tianai-captcha.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>${commons-net.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>logback-adapter</artifactId>
                <version>${nacos.logback-adapter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openjdk.nashorn</groupId>
                <artifactId>nashorn-core</artifactId>
                <version>${nashorn.version}</version>
            </dependency>
            <!--      amazon SDK      -->
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${amazon.aws.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>dingtalk</artifactId>
                <version>${dingtalk.server.new.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>alibaba-dingtalk-service-sdk</artifactId>
                <version>${dingtalk.server.old.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.googlecode.libphonenumber</groupId>
                <artifactId>libphonenumber</artifactId>
                <version>${libphonenumber.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-netty</artifactId>
                <version>${grpc-netty.version}</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>ocr_api20210707</artifactId>
                <version>${aliyun.ocr.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>${jsqlparser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${alibaba.transmittable.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcpkix-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>

            <!--      smart-boot      -->
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-system</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-auth-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-auth-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-auth</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-code</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-document</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-tool-database</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-file</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-message</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-module-monitor-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-actuator</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-access-secret</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-cache-guava</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-cache-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-captcha</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-jwt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-saml2</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-sms</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-wechat</artifactId>
                <version>${project.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-captcha</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-crud</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-dingtalk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-document</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-aliyun</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-disk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-ftp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-minio</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-qiniu</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-s3</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-file-sftp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-freemarker</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-guava</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-i18n</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-kettle</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-license-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-license-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-log</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-message-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-message-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-message-dingtalk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-message-email</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-message-sms-aliyun</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-message-sms-tencent</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-message-websocket</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-monitor-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-monitor-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-tool-database</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-wechat</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-xxl</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-starter-auth</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-auth-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-starter-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-starter-feign</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-starter-i18n</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-cloud-starter-log</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-ai-dify</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-druid</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.smart</groupId>
                <artifactId>smart-boot-starter-ai-langchain4j</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.name}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.18.0</version>
                <configuration>
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <attach>true</attach>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <release>${java.version}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>smart-boot</id>
            <url>https://maven.gc-it.cn/repository/maven-public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>smart-boot</id>
            <url>https://maven.gc-it.cn/repository/maven-public/</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>releases</id>
            <url>https://maven.gc-it.cn/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <url>https://maven.gc-it.cn/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>
