<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot-framework</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-boot-autoconfigure</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <name>smart-boot-autoconfigure</name>
    <description>项目自动配置模块</description>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

        <!--    crud    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-crud</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
            <optional>true</optional>
        </dependency>

        <!--    exception    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-exception</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    log    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-log</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    file    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-aliyun-oss</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-disk</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-ftp</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-minio</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-qiniu</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-s3</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-sftp</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-file-extensions-sftp-sshj</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    redis    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-redis</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <optional>true</optional>
        </dependency>

        <!--    guava    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-cache-guava</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    i18n    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-i18n</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    dingtalk    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-extensions-dingtalk</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    wechat    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-extensions-wechat</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-miniapp</artifactId>
            <optional>true</optional>
        </dependency>

        <!--    captcha    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-extensions-captcha</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    xxl-job    -->
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <optional>true</optional>
        </dependency>

        <!--    auth    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-cache-guava</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-cache-redis</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-jwt</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-access-secret</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-sms</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-wechat</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-dingtalk</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <!--    tool-database    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-tool-database</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    license    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-license-client</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-license-server</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    消息模块    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extension-dingtalk</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extension-email</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extensions-sms-aliyun</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extensions-sms-tencent</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extension-websocket</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-message-extension-wechat</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    文档工具    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-document-code-zxing</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-document-converter-jod</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-document-converter-office</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-document-excel-jxls</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    KETTLE    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-kettle</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <!--    monitor    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-monitor-client</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-monitor-server</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator-autoconfigure</artifactId>
        </dependency>

        <!--    freemarker    -->
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-freemarker</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-ai-dify</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-druid-enhance</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-3-starter</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-web</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-auth-extensions-domain</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-ai-langchain4j</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-webmvc</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-mail</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-authorization-server</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-rocketmq</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-n8n</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
