spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
    url: jdbc:mysql://localhost:3306/smart-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  data:
    redis:
      host: localhost
      password: password

logging:
  level:
    root: info
    com.smart: info

smart:
  auth:
    ignores:
      get:
        - .html
        - /doc.html
        - /webjars/**
        - /v3/api-docs/**
