<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.smart</groupId>
		<artifactId>smart-message-extension-sms</artifactId>
		<version>5.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>smart-message-extensions-sms-aliyun</artifactId>
	<version>5.0.0-SNAPSHOT</version>
	<name>smart-message-extensions-sms-aliyun</name>
	<description>阿里云短信服务</description>

	<properties>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-message-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.aliyun</groupId>
			<artifactId>dysmsapi20170525</artifactId>
		</dependency>

		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-commons-core</artifactId>
		</dependency>

		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-commons-validate</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>


</project>
