<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.smart</groupId>
		<artifactId>smart-file</artifactId>
		<version>5.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>smart-file-extensions-s3</artifactId>
	<version>5.0.0-SNAPSHOT</version>
	<name>smart-file-extensions-s3</name>
	<description>amazon S3 对象存储扩展</description>

	<properties>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-file-core</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>

		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3</artifactId>
		</dependency>
	</dependencies>


</project>
