server:
  port: 8094

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: @profiles.active@
      config:
        namespace: @profiles.active@
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml