<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot-starters</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-boot-starter-message</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <name>smart-boot-starter-message</name>
    <description>message模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>smart-boot-starter-message-dingtalk</module>
        <module>smart-boot-starter-message-email</module>
        <module>smart-boot-starter-message-sms-aliyun</module>
        <module>smart-boot-starter-message-sms-tencent</module>
        <module>smart-boot-starter-message-websocket</module>
        <module>smart-boot-starter-message-wechat</module>
    </modules>

    <properties>
    </properties>

    <dependencies>
    </dependencies>


</project>
