server:
  port: 8092

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      server-addr: @nacos.server-addr@
      discovery:
        namespace: @nacos.namespace@
        ip: @nacos.ip@
      config:
        namespace: @nacos.namespace@
      username: @nacos.username@
      password: @nacos.password@
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml