<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-framework</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <name>smart-framework</name>
    <description>框架代码</description>
    <packaging>pom</packaging>

    <modules>
        <module>smart-ai</module>
        <module>smart-auth</module>
        <module>smart-cache-guava</module>
        <module>smart-commons</module>
        <module>smart-crud</module>
        <module>smart-document</module>
        <module>smart-druid-enhance</module>
        <module>smart-exception</module>
        <module>smart-extensions</module>
        <module>smart-file</module>
        <module>smart-freemarker</module>
        <module>smart-i18n</module>
        <module>smart-kettle</module>
        <module>smart-license</module>
        <module>smart-log</module>
        <module>smart-message</module>
        <module>smart-monitor</module>
        <module>smart-redis</module>
        <module>smart-tools</module>
    </modules>

    <properties>
    </properties>

    <dependencies>

    </dependencies>


</project>
