<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot-framework</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-boot-module</artifactId>
    <name>smart-boot-module</name>
    <description>smart-boot自动配置模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>smart-boot-ai</module>
        <module>smart-boot-auth</module>
        <module>smart-boot-guava</module>
        <module>smart-boot-captcha</module>
        <module>smart-boot-crud</module>
        <module>smart-boot-dingtalk</module>
        <module>smart-boot-document</module>
        <module>smart-boot-druid</module>
        <module>smart-boot-exception</module>
        <module>smart-boot-file</module>
        <module>smart-boot-freemarker</module>
        <module>smart-boot-i18n</module>
        <module>smart-boot-kettle</module>
        <module>smart-boot-license-client</module>
        <module>smart-boot-license-server</module>
        <module>smart-boot-log</module>
        <module>smart-boot-message</module>
        <module>smart-boot-monitor-client</module>
        <module>smart-boot-monitor-server</module>
        <module>smart-boot-n8n</module>
        <module>smart-boot-redis</module>
        <module>smart-boot-rocketmq</module>
        <module>smart-boot-tool-database</module>
        <module>smart-boot-wechat</module>
        <module>smart-boot-xxl</module>

        <module>smart-boot-demo</module>
    </modules>

    <properties>
    </properties>

    <dependencies>

    </dependencies>


</project>
