spring:
  cloud:
    gateway:
      server:
        webflux:
          # 开启网关的跨域功能，具体微服务上的跨域需要进行关闭，否则无效
          globalcors:
            cors-configurations:
              '[/**]': # 匹配所有请求
                allowedOrigins: "*" # 跨域处理 允许所有的域
                allowedHeaders: "*"
                allowedMethods: # 支持的方法
                  - GET
                  - POST
                  - PUT
                  - DELETE
          routes:
            - id: smart-cloud-service-auth
              uri: lb://smart-cloud-service-auth
              predicates:
                - Path=/smart-auth/**
              filters:
                - StripPrefix=1
            - id: smart-cloud-service-system
              uri: lb://smart-cloud-service-system
              predicates:
                - Path=/smart-system/**
              filters:
                - StripPrefix=1
            - id: smart-cloud-service-code
              uri: lb://smart-cloud-service-code
              predicates:
                - Path=/smart-code/**
              filters:
                - StripPrefix=1
            - id: smart-cloud-service-file
              uri: lb://smart-cloud-service-file
              predicates:
                - Path=/smart-file/**
              filters:
                - StripPrefix=1
            - id: smart-cloud-service-message
              uri: lb://smart-cloud-service-message
              predicates:
                - Path=/smart-message/**
              filters:
                - StripPrefix=1
            #        海道网内贸订舱
            - id: spgline-domestic-booking
              uri: lb://spgline-domestic-booking
              predicates:
                - Path=/spgline-domestic-booking/**
              filters:
                - StripPrefix=1