<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.smart</groupId>
        <artifactId>smart-boot-document</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-boot-document-converter-office</artifactId>
    <name>smart-boot-document-converter-office</name>
    <description>smart-boot-document-converter-office</description>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-document-converter-office</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
