<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.smart</groupId>
		<artifactId>smart-services</artifactId>
		<version>5.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>smart-service-system</artifactId>
	<version>5.0.0-SNAPSHOT</version>
	<name>smart-service-system</name>
	<description>服务-系统管理</description>

	<modules>

	</modules>

	<properties>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-module-system</artifactId>
		</dependency>

		<!--	引入认证支持 	-->
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-module-auth</artifactId>
		</dependency>

		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-auth-jwt</artifactId>
		</dependency>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-auth-cache-redis</artifactId>
		</dependency>


		<!--	基础支持：国际化、异常处理	-->
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-i18n</artifactId>
		</dependency>

		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-druid</artifactId>
		</dependency>

		<!--	消息支持	-->
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-module-message</artifactId>
		</dependency>
		<!--	web socket支持	-->
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-message-websocket</artifactId>
		</dependency>

		<!--	代码生成器	-->
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-module-code</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!--	数据库	-->
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-file-aliyun</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-module-file</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-auth-aksk</artifactId>
		</dependency>
		<dependency>
			<groupId>com.smart</groupId>
			<artifactId>smart-boot-starter-auth-domain</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot.version}</version>
				<configuration>
					<mainClass>com.smart.service.system.SmartServiceSystemApplication</mainClass>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<encoding>UTF-8</encoding>
					<!-- 过滤后缀文件 -->
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
						<nonFilteredFileExtension>xls</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
