server:
  port: 9095

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2060MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
    system:
      url: jdbc:mysql://localhost:3306/smart-system2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ming8858

logging:
  level:
    root: info
    com.smart: debug

smart:
  file:
    basePath: C:\Users\ShiZhong\Documents\workspace\temp\file_server\
  auth:
    development: false
    ignores:
      pattern:
        - /actuator/**

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
