server:
  port: 9095

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      stat-view-servlet:
#        enabled: true
#        login-username: root
#        login-password: root
    system:
      url: jdbc:mysql://localhost:3306/smart-system2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ming8858

logging:
  level:
    root: info
    com.smart: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

smart:
  file:
    basePath: E:\Documents\workspace\temp\fileServer
  auth:
    ignores:
      pattern:
        - /actuator/**
  monitor:
    client:
      registration:
        url: http://localhost:9095
      instance:
        name: smart-system
    server:
      dataSync:
        log:
          enabled: false


management:
  endpoint:
    #    开启shutdown端点
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
