server:
  port: 9095

spring:
  redis:
    host: one.smart-ming.online
    password: ming8858
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
    system:
      url: jdbc:mysql://one.smart-ming.online:3306/smart-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ming8858

logging:
  level:
    root: info
    com.smart: debug

management:
  endpoint:
    #    开启shutdown端点
    shutdown:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
smart:
  auth:
    ignores:
      get:
        - .html
        - /doc.html
        - /webjars/**
        - /v3/api-docs/**
      pattern:
        - /xrebel/**
    method: true
  license:
    client:
      key:
        subject: CESHI123
        publicAlias: publicCert
        storePass: public_password1234
        licensePath: D:\zhongming\Documents\01-workspace\06-temp\keystore\license.lic
        publicKeysStorePath: D:\zhongming\Documents\01-workspace\06-temp\keystore\publicCerts.keystore
      project:
        enterprise: ''
        project: ''
        version: ''
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
