<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>smart-framework</artifactId>
        <groupId>com.smart</groupId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>smart-n8n</artifactId>
    <name>smart-n8n</name>
    <description>n8n client for smart framework</description>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.smart</groupId>
            <artifactId>smart-commons-core</artifactId>
        </dependency>
    </dependencies>
</project>